version: '3.3'

services:
  pydemo:
    build: .
    container_name: pydemo
    ports:
      - 8888:8888
    volumes:
      - "${PWD}/src:/opt/workspace"
    entrypoint: "python3 /opt/workspace/demo.py"
  redis:
    image: redis:latest