version: '3.3'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft-java
    environment:
      EULA: "TRUE"
      TZ: "Australia/Melbourne"
    ports:
      - 25565:25565
    volumes:
      - ${PWD}/minecraft-data/java:/data"
